// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
//import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaSxCZ8-WzgRk00reqbgDWjs2s2seZEeU',
    appId: '1:597939814331:web:2639e71f69f40d9166ce9e',
    messagingSenderId: '597939814331',
    projectId: 'jamapp-63c8f',
    authDomain: 'jamapp-63c8f.firebaseapp.com',
    storageBucket: 'jamapp-63c8f.appspot.com',
    measurementId: 'G-VEWNY08F8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzOo8pmyaUOJ2oHUbomQ2S2bpRZIiqXzQ',
    appId: '1:597939814331:android:b9d6e91974c0c8ec66ce9e',
    messagingSenderId: '597939814331',
    projectId: 'jamapp-63c8f',
    storageBucket: 'jamapp-63c8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQxMfbvoWVXovBY9gquQzS8BxRg7R-S9A',
    appId: '1:597939814331:ios:0886de3092d3685366ce9e',
    messagingSenderId: '597939814331',
    projectId: 'jamapp-63c8f',
    storageBucket: 'jamapp-63c8f.appspot.com',
    iosBundleId: 'com.example.jamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQxMfbvoWVXovBY9gquQzS8BxRg7R-S9A',
    appId: '1:597939814331:ios:0886de3092d3685366ce9e',
    messagingSenderId: '597939814331',
    projectId: 'jamapp-63c8f',
    storageBucket: 'jamapp-63c8f.appspot.com',
    iosBundleId: 'com.example.jamapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaSxCZ8-WzgRk00reqbgDWjs2s2seZEeU',
    appId: '1:597939814331:web:db959fab4fc7068066ce9e',
    messagingSenderId: '597939814331',
    projectId: 'jamapp-63c8f',
    authDomain: 'jamapp-63c8f.firebaseapp.com',
    storageBucket: 'jamapp-63c8f.appspot.com',
    measurementId: 'G-4L568ZFJKT',
  );

}